#!/usr/bin/env python3
"""
plot_wsb_vs_artemis_circularize.py
  Animated comparison:
    • WSB ballistic capture + LOI burn → lunar orbit
    • Artemis II trajectory + LOI burn → lunar orbit

  Loads:
    out/wsb_circularize/capture.csv
    out/wsb_circularize/loi_orbit.csv
    out/wsb_circularize/circularize_info.txt
    out/artemis_circularize/loi_orbit.csv
    out/artemis_circularize/info.txt
    Artemis/out/artemis2_trajectory.csv

  Outputs (saved to out/wsb_circularize/):
    wsb_circ_3d.html   -- interactive Plotly 3D
    wsb_circ.mp4       -- MP4 video

Run from AstroProbs/LunarTrajectories/:
  python plot/plot_wsb_vs_artemis_circularize.py
"""
from __future__ import annotations

import datetime
import pathlib
import sys

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from mpl_toolkits.mplot3d import Axes3D  # noqa: F401

# ── Shared constants and frame utilities ──────────────────────────────────────
from wsb_style import (
    MU, L_KM, T_STAR, R_EARTH, R_MOON, R_HILL_ND, R_HILL_KM,
    rot_em_to_eci, moon_em_to_eci, orbital_plane_r3d,
)
from astrodynamics import MOON_SIDEREAL_DAYS, SYNODIC_DAYS

# ── Paths ─────────────────────────────────────────────────────────────────────
_HERE         = pathlib.Path(__file__).parent
ROOT          = _HERE.parent
WSB_DIR       = ROOT / "out" / "wsb"
ART_DIR       = ROOT.parent / "Artemis" / "out"
ART_CSV       = ART_DIR  / "artemis2_trajectory.csv"
ART_CIRC_DIR  = ROOT / "out" / "artemis_circularize"
WSB_HIF_CSV   = WSB_DIR / "solution_hifi.csv"
CAPTURE_CSV   = WSB_DIR / "capture.csv"
LOI_CSV       = WSB_DIR / "loi_orbit.csv"
EPOCH_INFO    = WSB_DIR / "epoch_info.txt"
CIRC_INFO     = WSB_DIR / "circularize_info.txt"
ART_LOI_CSV   = ART_CIRC_DIR / "loi_orbit.csv"
ART_CIRC_INFO = ART_CIRC_DIR / "info.txt"
MOON_EPHEM_CSV = ART_DIR / "moon_ephem.csv"
OUT_HTML      = WSB_DIR / "wsb_circ_3d.html"
OUT_MP4       = WSB_DIR / "wsb_circ.mp4"

V_STAR_KMS  = L_KM / T_STAR
R_PARK_ND   = (6_371.0 + 378.0) / L_KM
R_PARK_KM   = R_PARK_ND * L_KM
# Artemis parking orbit (config.rs: parking_apogee_alt_m = 109_400_000)
ART_PARKING_APO_KM = R_EARTH + 109_400.0   # 115 771 km
ART_TLI_KMS        = 0.4224                # TLI from parking orbit (config delta_v_ms)

# Artemis TLI epoch (config.rs: April 2 2026 23:49 UTC).
TLI_UTC = datetime.datetime(2026, 4, 2, 23, 49, 0, tzinfo=datetime.timezone.utc)

# ── Style ─────────────────────────────────────────────────────────────────────
BG          = "#0F0F19"
COL_CAP     = "#00E5FF"   # cyan  — WSB ballistic capture
COL_LOI     = "#39FF14"   # neon green — WSB post-LOI lunar orbit
COL_ART     = "#FF8C00"   # orange — Artemis II capture
COL_ART_LOI = "#FFB347"   # light orange — Artemis post-LOI lunar orbit
COL_BURN    = "#FF00FF"   # magenta — WSB LOI burn marker
COL_BURN_A  = "#FF4444"   # red — Artemis LOI burn marker
COL_TLI     = "#FFD700"   # gold — TLI departure markers
COL_EARTH   = "#1565C0"
COL_MOON    = "#9E9E9E"
COL_HILL    = "#BA7517"


def compute_eci_frame(moon_x_m, moon_y_m, moon_z_m, time_s):
    """Build R0: 3×3 EM-inertial → ECI. Wrapper around orbital_plane_r3d."""
    m0_km    = np.array([moon_x_m[0], moon_y_m[0], moon_z_m[0]]) / 1e3
    m1_km    = np.array([moon_x_m[1], moon_y_m[1], moon_z_m[1]]) / 1e3
    dt       = float(time_s[1] - time_s[0])
    m_vel_km = (m1_km - m0_km) / dt
    return orbital_plane_r3d(m0_km, m_vel_km)



def load_moon_ephem(art_t_s0: float) -> tuple:
    """Load DE440S Moon+Sun ephemeris from moon_ephem.csv (generated by moon_ephem Rust binary).
    Returns (t_days, mx_km, my_km, mz_km, sx_km, sy_km, sz_km) in days from Artemis CSV start."""
    df     = pd.read_csv(MOON_EPHEM_CSV)
    t_days = (df["time_s"].values - art_t_s0) / 86_400.0
    return (t_days,
            df["moon_x_m"].values * 1e-3, df["moon_y_m"].values * 1e-3, df["moon_z_m"].values * 1e-3,
            df["sun_x_m"].values  * 1e-3, df["sun_y_m"].values  * 1e-3, df["sun_z_m"].values  * 1e-3)


def _interp_ephem(t_days: float, ephem_t, ex, ey, ez) -> np.ndarray:
    """Interpolate ephemeris position (km) at t_days from Artemis CSV start."""
    return np.array([np.interp(t_days, ephem_t, ex),
                     np.interp(t_days, ephem_t, ey),
                     np.interp(t_days, ephem_t, ez)])


def compute_wsb_epoch_simple(
    theta_sun_deg: float,
    R0: np.ndarray,
    u_sun_eci: np.ndarray,
    burn_time_days: float = 0.0,
    target_loi_days: float = 5.0,
) -> tuple:
    """Circular-Moon WSB epoch — mirrors plot_wsb_vs_artemis.py's compute_wsb_epoch,
    extended with synodic N selection to place the LOI near target_loi_days."""
    if np.isnan(theta_sun_deg):
        return 0.0, R0.copy()
    sun_in_em         = R0.T @ u_sun_eci
    theta_sun_artemis = np.degrees(np.arctan2(sun_in_em[1], sun_in_em[0]))
    delta_theta       = ((theta_sun_deg - theta_sun_artemis) + 180.0) % 360.0 - 180.0
    offset_days_base  = delta_theta / (-360.0 / SYNODIC_DAYS)
    target_dep        = target_loi_days - burn_time_days
    best_N            = round((target_dep - offset_days_base) / SYNODIC_DAYS)
    offset_days       = offset_days_base + best_N * SYNODIC_DAYS
    print(f"  Synodic N={best_N:+d}: departure={offset_days:.2f} d, LOI @ {offset_days + burn_time_days:.2f} d")
    moon_angle_rad = 2.0 * np.pi * offset_days / MOON_SIDEREAL_DAYS
    ca, sa = np.cos(moon_angle_rad), np.sin(moon_angle_rad)
    new_x  = R0 @ np.array([ca, sa, 0.0])
    new_z  = R0[:, 2]
    new_y  = np.cross(new_z, new_x); new_y /= np.linalg.norm(new_y)
    R0_wsb = np.column_stack([new_x, new_y, new_z])
    return offset_days, R0_wsb


def compute_wsb_epoch(theta_sun_deg, R0, u_sun_eci,
                      ephem_t, ephem_mx, ephem_my, ephem_mz,
                      ephem_sx, ephem_sy, ephem_sz,
                      burn_time_days: float = 0.0,
                      target_loi_days: float = 5.0):
    """Find WSB departure epoch from BCR4BP Sun angle using DE440S ephemeris.

    Uses real Moon+Sun positions (interpolated from DE440S) instead of 2-body
    propagation, eliminating solar-perturbation error.

    Step 1 — mean-synodic initial guess (±14.8 d, one synodic root).
    Step 2 — pick synodic N to place WSB LOI near target_loi_days.
    Step 3 — Newton refinement: match real Sun angle to theta_sun_deg.
    Step 4 — build R0_wsb from real Moon direction at the converged epoch.
    """
    if np.isnan(theta_sun_deg):
        return 0.0, R0.copy()

    # ── Step 1: mean-synodic initial guess ──────────────────────────────────────
    sun_in_em         = R0.T @ u_sun_eci
    theta_sun_artemis = np.degrees(np.arctan2(sun_in_em[1], sun_in_em[0]))
    delta_theta       = ((theta_sun_deg - theta_sun_artemis) + 180.0) % 360.0 - 180.0
    offset_days_base  = delta_theta / (-360.0 / SYNODIC_DAYS)

    # ── Step 2: synodic N that puts WSB LOI nearest to Artemis LOI ──────────────
    target_dep  = target_loi_days - burn_time_days
    best_N      = round((target_dep - offset_days_base) / SYNODIC_DAYS)
    offset_days = offset_days_base + best_N * SYNODIC_DAYS
    print(f"  Synodic N={best_N:+d}: departure={offset_days:.2f} d, "
          f"WSB LOI @ {offset_days + burn_time_days:.2f} d  "
          f"(Artemis LOI ~ {target_loi_days:.1f} d)")
    offset_days_mean = float(offset_days)

    # ── Step 3: Newton refinement using DE440S ───────────────────────────────────
    z_em = R0[:, 2]
    for _ in range(8):
        m_wsb      = _interp_ephem(offset_days, ephem_t, ephem_mx, ephem_my, ephem_mz)
        s_wsb      = _interp_ephem(offset_days, ephem_t, ephem_sx, ephem_sy, ephem_sz)
        em_x       = m_wsb / np.linalg.norm(m_wsb)
        em_y_n     = np.cross(z_em, em_x); em_y_n /= np.linalg.norm(em_y_n)
        theta_real = np.degrees(np.arctan2(s_wsb @ em_y_n, s_wsb @ em_x))
        residual   = ((theta_sun_deg - theta_real) + 180.0) % 360.0 - 180.0
        offset_days += residual / (-360.0 / SYNODIC_DAYS)
        if abs(residual) < 1e-6:
            break
    print(f"  Newton refinement: {offset_days_mean:.4f} d -> {offset_days:.4f} d  "
          f"(delta = {(offset_days - offset_days_mean)*24:.2f} h)")

    # ── Step 4: R0_wsb from real Moon direction at departure ─────────────────────
    moon_at_wsb = _interp_ephem(offset_days, ephem_t, ephem_mx, ephem_my, ephem_mz)
    new_x  = moon_at_wsb / np.linalg.norm(moon_at_wsb)
    new_z  = R0[:, 2]
    new_y  = np.cross(new_z, new_x); new_y /= np.linalg.norm(new_y)
    R0_wsb = np.column_stack([new_x, new_y, new_z])
    return offset_days, R0_wsb


# ══════════════════════════════════════════════════════════════════════════════
# Data loading
# ══════════════════════════════════════════════════════════════════════════════

def load_artemis():
    df  = pd.read_csv(ART_CSV)
    t_s = df["time_s"].values
    sc  = df[["x_m", "y_m", "z_m"]].values * 1e-3
    mn  = df[["moon_x_m", "moon_y_m", "moon_z_m"]].values * 1e-3
    sn  = df[["sun_x_m", "sun_y_m", "sun_z_m"]].values * 1e-3
    u_sun_eci = sn[0] / np.linalg.norm(sn[0])
    R0 = compute_eci_frame(df["moon_x_m"].values, df["moon_y_m"].values,
                           df["moon_z_m"].values, t_s)

    t_rel = t_s - t_s[0]
    mask  = t_rel >= 6 * 86_400.0
    if mask.any():
        offset = int(np.where(mask)[0][0])
        end    = offset + int(np.argmin(np.linalg.norm(sc[mask], axis=1)))
        sc, mn, t_s = sc[:end+1], mn[:end+1], t_s[:end+1]
    t_days = (t_s - t_s[0]) / 86_400.0
    return (R0, u_sun_eci,
            t_days, sc[:,0], sc[:,1], sc[:,2],
            mn[:,0], mn[:,1], mn[:,2])


def _load_wsb_nd_csv(path: pathlib.Path, R0_wsb, offset_days):
    """Rotating-frame CSV → ECI days + moon ECI."""
    df = pd.read_csv(path)
    t  = df["time_nd"].values
    x, y, z = df["x_nd"].values, df["y_nd"].values, df["z_nd"].values
    xi, yi, zi = rot_em_to_eci(x, y, z, t, R0_wsb)
    mx, my, mz = moon_em_to_eci(t, R0_wsb)
    t_days = t * T_STAR / 86_400.0 + offset_days
    return t_days, xi, yi, zi, mx, my, mz


def load_wsb_epoch(R0, u_sun_eci,
                   ephem_t, ephem_mx, ephem_my, ephem_mz,
                   ephem_sx, ephem_sy, ephem_sz,
                   burn_time_days: float = 0.0,
                   target_loi_days: float = 5.0):
    meta = pd.read_csv(WSB_HIF_CSV, nrows=1).iloc[0]
    theta_sun_deg = float(meta["theta_sun_deg"])
    print(f"  theta_sun_deg = {theta_sun_deg:.4f} deg")
    return compute_wsb_epoch(theta_sun_deg, R0, u_sun_eci,
                             ephem_t, ephem_mx, ephem_my, ephem_mz,
                             ephem_sx, ephem_sy, ephem_sz,
                             burn_time_days=burn_time_days,
                             target_loi_days=target_loi_days)


def load_circ_info(path: pathlib.Path) -> dict:
    info = {}
    if not path.exists():
        return info
    for line in path.read_text().splitlines():
        if ":" in line:
            k, _, v = line.partition(":")
            info[k.strip()] = v.strip()
    return info


def load_epoch_info() -> tuple:
    """Read dep_offset_days and R0_wsb from Rust-generated epoch_info.txt."""
    info = {}
    for line in EPOCH_INFO.read_text().splitlines():
        if ":" in line:
            k, _, v = line.partition(":")
            info[k.strip()] = v.strip()
    dep_offset_days = float(info["dep_offset_days"])
    R0_wsb = np.array([
        [float(x) for x in info["R0_wsb_col0"].split()],
        [float(x) for x in info["R0_wsb_col1"].split()],
        [float(x) for x in info["R0_wsb_col2"].split()],
    ]).T   # columns → matrix
    return dep_offset_days, R0_wsb


def load_wsb_loi_eci(art_t_s0: float):
    """Load WSB ECI LOI orbit CSV (same format as Artemis) → (t_days, x, y, z, mx, my, mz)."""
    df     = pd.read_csv(LOI_CSV)
    t_days = (df["time_s"].values - art_t_s0) / 86_400.0
    return (t_days,
            df["x_km"].values,  df["y_km"].values,  df["z_km"].values,
            df["moon_x_km"].values, df["moon_y_km"].values, df["moon_z_km"].values)


def load_artemis_loi(art_t_s0: float):
    """Load Artemis LOI orbit CSV → (t_days_from_art_dep, x, y, z, mx, my, mz)."""
    df     = pd.read_csv(ART_LOI_CSV)
    t_days = (df["time_s"].values - art_t_s0) / 86_400.0
    return (t_days,
            df["x_km"].values,  df["y_km"].values,  df["z_km"].values,
            df["moon_x_km"].values, df["moon_y_km"].values, df["moon_z_km"].values)


# ══════════════════════════════════════════════════════════════════════════════
# Geometry helpers
# ══════════════════════════════════════════════════════════════════════════════

def sphere_surface(r, nu=40, nv=20):
    u = np.linspace(0, 2 * np.pi, nu)
    v = np.linspace(0, np.pi, nv)
    return (r * np.outer(np.cos(u), np.sin(v)),
            r * np.outer(np.sin(u), np.sin(v)),
            r * np.outer(np.ones(nu), np.cos(v)))


def downsample(arr, n):
    idx = np.unique(np.round(np.linspace(0, len(arr) - 1, n)).astype(int))
    return arr[idx]


def interp_pos(t_arr, x, y, z, t_query):
    tq = np.clip(t_query, t_arr[0], t_arr[-1])
    return np.interp(tq, t_arr, x), np.interp(tq, t_arr, y), np.interp(tq, t_arr, z)


def hohmann_tli_dv(r_park_km: float, r_apo_km: float,
                   gm_earth: float = 398_600.4418) -> float:
    """ΔV to raise apogee from circular parking orbit to r_apo via Hohmann."""
    a_t    = (r_park_km + r_apo_km) / 2.0
    v_circ = np.sqrt(gm_earth / r_park_km)
    v_tli  = np.sqrt(gm_earth * (2.0 / r_park_km - 1.0 / a_t))
    return v_tli - v_circ


# ══════════════════════════════════════════════════════════════════════════════
# Plot 1 — interactive Plotly 3D HTML
# ══════════════════════════════════════════════════════════════════════════════

def build_plotly(
    cap_t, cap_x, cap_y, cap_z, cap_mx, cap_my, cap_mz,
    loi_t, loi_x, loi_y, loi_z, loi_mx, loi_my, loi_mz,
    art_t, art_x, art_y, art_z, art_mx, art_my, _art_mz,
    art_loi_t, art_loi_x, art_loi_y, art_loi_z,
    art_loi_mx, art_loi_my, _art_loi_mz,
    burn_t: float,
    burn_t_art: float,
    wsb_circ_info: dict,
    art_circ_info: dict,
    R0: np.ndarray,
    wsb_tli_dv: float = 0.0,
    art_tli_dv: float = 0.0,
    art_parking_dv: float = 0.0,
    art_t_s0: float = 0.0,
    de440s_moon_t: np.ndarray = None,
    de440s_moon_x: np.ndarray = None,
    de440s_moon_y: np.ndarray = None,
    de440s_moon_z: np.ndarray = None,
) -> go.Figure:

    N_FRAMES = 500
    FRAME_MS = 30

    t_min    = cap_t[0]
    t_max    = max(loi_t[-1], art_loi_t[-1])
    frames_t = np.linspace(t_min, t_max, N_FRAMES)

    if de440s_moon_t is not None:
        _emx = lambda t: np.interp(t, de440s_moon_t, de440s_moon_x)
        _emy = lambda t: np.interp(t, de440s_moon_t, de440s_moon_y)
    else:
        _emx = lambda t: np.interp(t, cap_t, cap_mx)
        _emy = lambda t: np.interp(t, cap_t, cap_my)
    # Capture arc: circular-Moon subtraction (consistent with rot_em_to_eci)
    cap_xmc     = cap_x - cap_mx;              cap_ymc     = cap_y - cap_my
    # LOI orbit and Artemis: DE440S subtraction (ECI already uses DE440S Moon)
    loi_xmc     = loi_x     - _emx(loi_t);     loi_ymc     = loi_y     - _emy(loi_t)
    art_xmc     = art_x     - _emx(art_t);     art_ymc     = art_y     - _emy(art_t)
    art_loi_xmc = art_loi_x - _emx(art_loi_t); art_loi_ymc = art_loi_y - _emy(art_loi_t)
    _art_burn_mx = float(_emx(burn_t_art)); _art_burn_my = float(_emy(burn_t_art))

    sx, sy, sz = sphere_surface(R_EARTH * 3.5)
    _t_orb = np.linspace(0, 2 * np.pi, 361)
    _morb  = R0 @ (np.array([np.cos(_t_orb), np.sin(_t_orb), np.zeros(361)]) * L_KM)

    r_wsb     = np.sqrt(cap_x**2 + cap_y**2 + cap_z**2)
    apo_idx   = int(np.argmax(r_wsb))
    apo_km    = float(r_wsb[apo_idx])
    r_art     = np.sqrt(art_x**2 + art_y**2 + art_z**2)
    art_apo_idx = int(np.argmax(r_art))
    art_apo_km  = float(r_art[art_apo_idx])
    r_eci_lim = max(float(np.max(np.abs([cap_x, cap_y, cap_z]))) * 1.08,
                   apo_km * 1.10)

    # Apogee distance rings (in the equatorial plane of R0)
    _phi_ring  = np.linspace(0, 2 * np.pi, 361)
    _wsb_ring  = R0 @ (np.array([np.cos(_phi_ring), np.sin(_phi_ring), np.zeros(361)]) * apo_km)
    _art_ring  = R0 @ (np.array([np.cos(_phi_ring), np.sin(_phi_ring), np.zeros(361)]) * art_apo_km)

    phi2d    = np.linspace(0, 2 * np.pi, 180)
    hill_x2d = R_HILL_KM * np.cos(phi2d)
    hill_y2d = R_HILL_KM * np.sin(phi2d)
    moon_rd  = R_MOON * 3
    moon_x2d = moon_rd * np.cos(phi2d)
    moon_y2d = moon_rd * np.sin(phi2d)

    fig = make_subplots(
        rows=1, cols=2,
        specs=[[{"type": "scene"}, {"type": "xy"}]],
        subplot_titles=["ECI Frame — Full Transfer + Lunar Orbit",
                        "Moon-Centred — Top-Down (SOI)"],
        column_widths=[0.56, 0.44],
        horizontal_spacing=0.06,
    )

    # ── Static ECI ────────────────────────────────────────────────────────────
    fig.add_trace(go.Surface(x=sx, y=sy, z=sz,
        colorscale=[[0,"#1A237E"],[0.5,COL_EARTH],[1,"#64B5F6"]],
        showscale=False, opacity=0.9, name="Earth",
        lighting=dict(ambient=0.6, diffuse=0.8, specular=0.4),
    ), row=1, col=1)

    fig.add_trace(go.Scatter3d(
        x=_morb[0], y=_morb[1], z=_morb[2], mode="lines",
        line=dict(color="rgba(180,180,180,0.25)", width=2.5),
        name="Moon orbit", hoverinfo="skip",
    ), row=1, col=1)

    # WSB apogee ring + marker
    fig.add_trace(go.Scatter3d(
        x=_wsb_ring[0].tolist(), y=_wsb_ring[1].tolist(), z=_wsb_ring[2].tolist(),
        mode="lines",
        line=dict(color=f"rgba(0,229,255,0.20)", width=1.5, dash="dot"),
        name=f"WSB apogee ring", hoverinfo="skip", showlegend=False,
    ), row=1, col=1)
    fig.add_trace(go.Scatter3d(
        x=[cap_x[apo_idx]], y=[cap_y[apo_idx]], z=[cap_z[apo_idx]],
        mode="markers+text",
        marker=dict(color=COL_CAP, size=7, symbol="diamond"),
        text=[f"WSB apogee {apo_km/1e3:.0f}e3 km"], textposition="top center",
        textfont=dict(color=COL_CAP, size=10), showlegend=False,
    ), row=1, col=1)
    # Artemis apogee ring + marker
    fig.add_trace(go.Scatter3d(
        x=_art_ring[0].tolist(), y=_art_ring[1].tolist(), z=_art_ring[2].tolist(),
        mode="lines",
        line=dict(color="rgba(255,140,0,0.20)", width=1.5, dash="dot"),
        name="Artemis apogee ring", hoverinfo="skip", showlegend=False,
    ), row=1, col=1)
    fig.add_trace(go.Scatter3d(
        x=[art_x[art_apo_idx]], y=[art_y[art_apo_idx]], z=[art_z[art_apo_idx]],
        mode="markers+text",
        marker=dict(color=COL_ART, size=7, symbol="diamond"),
        text=[f"Artemis apogee {art_apo_km/1e3:.0f}e3 km"], textposition="top center",
        textfont=dict(color=COL_ART, size=10), showlegend=False,
    ), row=1, col=1)

    # ── Animated ECI traces ────────────────────────────────────────────────────
    n0_eci = len(fig.data)
    for col, name in [(COL_CAP, "BC s/c"), (COL_LOI, "BC orbit"),
                       (COL_ART, "Artemis s/c"), (COL_ART_LOI, "Artemis orbit")]:
        fig.add_trace(go.Scatter3d(
            x=[], y=[], z=[], mode="markers",
            marker=dict(color=col, size=5, symbol="circle",
                        line=dict(color="white", width=0.8)),
            name=name, showlegend=False,
        ), row=1, col=1)
    fig.add_trace(go.Scatter3d(  # Moon dot
        x=[], y=[], z=[], mode="markers+text",
        marker=dict(color=COL_MOON, size=6),
        text=["Moon"], textposition="top center",
        textfont=dict(color=COL_MOON, size=9), showlegend=False,
    ), row=1, col=1)
    for col, name in [(COL_CAP, "Capture trail"), (COL_LOI, "BC orbit insertion trail"),
                       (COL_ART, "Artemis trail"), (COL_ART_LOI, "Artemis orbit insertion trail")]:
        fig.add_trace(go.Scatter3d(
            x=[], y=[], z=[], mode="lines",
            line=dict(color=col, width=4),
            name=name, showlegend=True,
        ), row=1, col=1)
    # anim_eci indices: 0-3=dots, 4=moon, 5-8=trails
    anim_eci = list(range(n0_eci, n0_eci + 9))

    # ── Static 2D SOI ─────────────────────────────────────────────────────────
    fig.add_trace(go.Scatter(
        x=hill_x2d.tolist(), y=hill_y2d.tolist(), mode="lines",
        line=dict(color=COL_HILL, width=2, dash="dot"),
        name=f"Hill sphere Moon ({R_HILL_KM/1e3:.0f}e3 km)",
    ), row=1, col=2)
    fig.add_trace(go.Scatter(
        x=moon_x2d.tolist(), y=moon_y2d.tolist(), mode="lines",
        fill="toself", fillcolor="rgba(160,160,160,0.5)",
        line=dict(color="#AAAAAA", width=1), showlegend=False,
    ), row=1, col=2)

    # ── Animated 2D SOI traces ─────────────────────────────────────────────────
    n0_soi = len(fig.data)
    for col in (COL_CAP, COL_LOI, COL_ART, COL_ART_LOI):
        fig.add_trace(go.Scatter(x=[], y=[], mode="lines",
            line=dict(color=col, width=3), showlegend=False,
        ), row=1, col=2)
    for col in (COL_CAP, COL_LOI, COL_ART, COL_ART_LOI):
        fig.add_trace(go.Scatter(x=[], y=[], mode="markers",
            marker=dict(color=col, size=7, symbol="circle",
                        line=dict(color="white", width=0.8)),
            showlegend=False,
        ), row=1, col=2)
    # Animated LOI burn markers in 2D (hidden until each burn fires)
    fig.add_trace(go.Scatter(
        x=[], y=[], mode="markers+text",
        marker=dict(color=COL_BURN, size=12, symbol="star"),
        text=["BC orbit insertion"], textposition="top center",
        textfont=dict(color=COL_BURN, size=9), showlegend=False,
    ), row=1, col=2)
    fig.add_trace(go.Scatter(
        x=[], y=[], mode="markers+text",
        marker=dict(color=COL_BURN_A, size=12, symbol="star"),
        text=["Artemis orbit insertion"], textposition="top center",
        textfont=dict(color=COL_BURN_A, size=9), showlegend=False,
    ), row=1, col=2)
    # 2D indices: 0-3 = trails, 4-7 = dots, 8 = wsb_loi_marker, 9 = art_loi_marker
    anim_soi = list(range(n0_soi, n0_soi + 10))

    ANIM_TRACES = anim_eci + anim_soi
    MAX_TRAIL   = 1200

    frames = []
    for fi, ft in enumerate(frames_t):
        past_wsb_burn = ft >= burn_t
        past_art_burn = ft >= burn_t_art

        cx,  cy,  cz  = interp_pos(cap_t, cap_x, cap_y, cap_z, min(ft, burn_t))
        lx,  ly,  lz  = interp_pos(loi_t, loi_x, loi_y, loi_z, ft)
        ax,  ay,  az  = interp_pos(art_t, art_x, art_y, art_z, min(ft, burn_t_art))
        alx, aly, alz = interp_pos(art_loi_t, art_loi_x, art_loi_y, art_loi_z, ft)

        # Moon dot: DE440S when available, else BCR4BP model fallback
        if de440s_moon_t is not None:
            mxw = float(np.interp(ft, de440s_moon_t, de440s_moon_x))
            myw = float(np.interp(ft, de440s_moon_t, de440s_moon_y))
            mzw = float(np.interp(ft, de440s_moon_t, de440s_moon_z))
        else:
            mxw = np.interp(min(ft, burn_t), cap_t, cap_mx) if not past_wsb_burn \
                  else np.interp(np.clip(ft, loi_t[0], loi_t[-1]), loi_t, loi_mx)
            myw = np.interp(min(ft, burn_t), cap_t, cap_my) if not past_wsb_burn \
                  else np.interp(np.clip(ft, loi_t[0], loi_t[-1]), loi_t, loi_my)
            mzw = np.interp(min(ft, burn_t), cap_t, cap_mz) if not past_wsb_burn \
                  else np.interp(np.clip(ft, loi_t[0], loi_t[-1]), loi_t, loi_mz)

        def _trail3(xs, ys, zs, mask):
            tx, ty, tz = xs[mask], ys[mask], zs[mask]
            if len(tx) > MAX_TRAIL:
                i = downsample(np.arange(len(tx)), MAX_TRAIL)
                tx, ty, tz = tx[i], ty[i], tz[i]
            return tx.tolist(), ty.tolist(), tz.tolist()

        cap_mask     = cap_t     <= min(ft, burn_t)
        loi_mask     = loi_t     <= ft
        art_mask     = art_t     <= min(ft, burn_t_art)
        art_loi_mask = art_loi_t <= ft

        ctx3,  cty3,  ctz3  = _trail3(cap_x,     cap_y,     cap_z,     cap_mask)
        ltx3,  lty3,  ltz3  = _trail3(loi_x,     loi_y,     loi_z,     loi_mask)
        atx3,  aty3,  atz3  = _trail3(art_x,      art_y,     art_z,     art_mask)
        altx3, alty3, altz3 = _trail3(art_loi_x,  art_loi_y, art_loi_z, art_loi_mask)

        def _trail2(xmc, ymc, mask):
            tx, ty = xmc[mask], ymc[mask]
            if len(tx) > MAX_TRAIL:
                i = downsample(np.arange(len(tx)), MAX_TRAIL)
                tx, ty = tx[i], ty[i]
            return tx.tolist(), ty.tolist()

        ctx2,  cty2  = _trail2(cap_xmc,     cap_ymc,     cap_mask)
        ltx2,  lty2  = _trail2(loi_xmc,     loi_ymc,     loi_mask)
        atx2,  aty2  = _trail2(art_xmc,      art_ymc,     art_mask)
        altx2, alty2 = _trail2(art_loi_xmc, art_loi_ymc, art_loi_mask)

        loi_3d = ([float(lx)], [float(ly)], [float(lz)]) if past_wsb_burn else ([], [], [])
        loi_2d = ([float(lx - mxw)], [float(ly - myw)]) if past_wsb_burn else ([], [])

        al_mx  = float(_emx(ft))
        al_my  = float(_emy(ft))
        al_3d  = ([float(alx)], [float(aly)], [float(alz)]) if past_art_burn else ([], [], [])
        al_2d  = ([float(alx - al_mx)], [float(aly - al_my)]) if past_art_burn else ([], [])

        wsb_loi_mk_2d = ([float(cap_xmc[-1])], [float(cap_ymc[-1])]) \
                        if past_wsb_burn else ([], [])
        art_loi_mk_2d = ([float(art_loi_x[0] - _art_burn_mx)], [float(art_loi_y[0] - _art_burn_my)]) \
                        if past_art_burn else ([], [])

        # 2D WSB dot during capture uses circular-Moon center (not DE440S)
        _cx_mc = float(np.interp(min(ft, burn_t), cap_t, cap_mx))
        _cy_mc = float(np.interp(min(ft, burn_t), cap_t, cap_my))

        frames.append(go.Frame(
            data=[
                # ECI dots: cap, loi, art, art_loi, moon
                go.Scatter3d(x=[float(cx)],  y=[float(cy)],  z=[float(cz)]),
                go.Scatter3d(x=loi_3d[0],   y=loi_3d[1],    z=loi_3d[2]),
                go.Scatter3d(x=[float(ax)],  y=[float(ay)],  z=[float(az)]),
                go.Scatter3d(x=al_3d[0],    y=al_3d[1],     z=al_3d[2]),
                go.Scatter3d(x=[float(mxw)], y=[float(myw)], z=[float(mzw)],
                             text=["Moon"], textposition="top center"),
                # ECI trails: cap, loi, art, art_loi
                go.Scatter3d(x=ctx3,  y=cty3,  z=ctz3),
                go.Scatter3d(x=ltx3,  y=lty3,  z=ltz3),
                go.Scatter3d(x=atx3,  y=aty3,  z=atz3),
                go.Scatter3d(x=altx3, y=alty3, z=altz3),
                # 2D trails: cap, loi, art, art_loi
                go.Scatter(x=ctx2,  y=cty2),
                go.Scatter(x=ltx2,  y=lty2),
                go.Scatter(x=atx2,  y=aty2),
                go.Scatter(x=altx2, y=alty2),
                # 2D dots: cap, loi, art, art_loi
                go.Scatter(x=[float(cx - _cx_mc)],  y=[float(cy - _cy_mc)]),
                go.Scatter(x=loi_2d[0],           y=loi_2d[1]),
                go.Scatter(x=[float(ax - al_mx)], y=[float(ay - al_my)]),
                go.Scatter(x=al_2d[0],            y=al_2d[1]),
                # 2D LOI burn markers
                go.Scatter(x=wsb_loi_mk_2d[0], y=wsb_loi_mk_2d[1],
                           text=["BC orbit insertion"] if past_wsb_burn else [],
                           textposition="top center"),
                go.Scatter(x=art_loi_mk_2d[0], y=art_loi_mk_2d[1],
                           text=["Artemis orbit insertion"] if past_art_burn else [],
                           textposition="top center"),
            ],
            traces=ANIM_TRACES, name=str(fi),
        ))
    fig.frames = frames

    # ft=0 corresponds to Artemis CSV start = TLI + art_t_s0 seconds
    _art_t0_utc = TLI_UTC + datetime.timedelta(seconds=art_t_s0)

    def _ft_to_utc(ft: float) -> str:
        return (_art_t0_utc + datetime.timedelta(days=ft)).strftime("%Y-%m-%d %H:%M")

    slider_steps = [
        {"args": [[str(fi)], {"frame": {"duration": FRAME_MS, "redraw": True},
                              "mode": "immediate", "transition": {"duration": 0}}],
         "label": _ft_to_utc(frames_t[fi]), "method": "animate"}
        for fi in range(0, N_FRAMES, max(1, N_FRAMES // 60))
    ]

    wsb_loi_dv   = float(wsb_circ_info.get("LOI DeltaV km/s", 0) or 0)
    art_loi_dv   = float(art_circ_info.get("LOI DeltaV km/s", 0) or 0)
    wsb_total_dv = wsb_tli_dv + wsb_loi_dv
    art_total_dv = art_parking_dv + art_tli_dv + art_loi_dv
    subtitle = (
        f"WSB:     TLI {wsb_tli_dv:.3f} + LOI {wsb_loi_dv:.3f} = <b>{wsb_total_dv:.3f} km/s</b>"
        f"   ·   "
        f"Artemis: Prk {art_parking_dv:.3f} + TLI {art_tli_dv:.3f} + LOI {art_loi_dv:.3f} = <b>{art_total_dv:.3f} km/s</b>"
    )

    def _ax3d(title, rng):
        return dict(showgrid=True, gridcolor="rgba(80,80,160,0.18)", zeroline=False,
                    tickfont=dict(size=8), title=title, range=rng)

    fig.update_layout(
        template="plotly_dark", paper_bgcolor="rgb(10,10,18)",
        scene=dict(
            bgcolor="rgb(12,12,22)",
            xaxis=_ax3d("X [km]", [-r_eci_lim, r_eci_lim]),
            yaxis=_ax3d("Y [km]", [-r_eci_lim, r_eci_lim]),
            zaxis=_ax3d("Z [km]", [-max(r_eci_lim*0.4, abs(float(cap_z[apo_idx]))*1.15),
                                    max(r_eci_lim*0.4, abs(float(cap_z[apo_idx]))*1.15)]),
            camera=dict(eye=dict(x=1.5, y=-2.2, z=1.0)),
            aspectmode="manual",
            aspectratio=dict(x=1.0, y=1.0,
                             z=max(0.4, abs(float(cap_z[apo_idx])) / r_eci_lim * 1.15)),
        ),
        xaxis=dict(title="X from Moon [km]",
                   range=[-R_HILL_KM*1.15, R_HILL_KM*1.15],
                   scaleanchor="y", scaleratio=1,
                   showgrid=True, gridcolor="rgba(80,80,160,0.18)",
                   tickfont=dict(size=9, color="#aaa")),
        yaxis=dict(title="Y from Moon [km]",
                   range=[-R_HILL_KM*1.15, R_HILL_KM*1.15],
                   showgrid=True, gridcolor="rgba(80,80,160,0.18)",
                   tickfont=dict(size=9, color="#aaa")),
        plot_bgcolor="rgb(12,12,22)",
        font=dict(color="white", size=11),
        title=dict(text="Ballistic capture vs Artemis II"
                        + (f"<br><sup>{subtitle}</sup>" if subtitle else ""),
                   x=0.01, xanchor="left"),
        legend=dict(x=0.01, y=0.98, font=dict(size=10),
                    bgcolor="rgba(15,15,25,0.7)"),
        height=740, margin=dict(l=0, r=0, t=95, b=80),
        updatemenus=[{
            "type": "buttons", "showactive": False,
            "x": 0.5, "xanchor": "center", "y": -0.08, "yanchor": "top",
            "buttons": [
                {"label": "Play", "method": "animate",
                 "args": [None, {"frame": {"duration": FRAME_MS, "redraw": True},
                                 "fromcurrent": True, "transition": {"duration": 0}}]},
                {"label": "Pause", "method": "animate",
                 "args": [[None], {"frame": {"duration": 0, "redraw": False},
                                   "mode": "immediate", "transition": {"duration": 0}}]},
            ],
            "font": {"color": "white"},
            "bgcolor": "rgba(40,40,60,0.9)", "bordercolor": "rgba(100,100,150,0.5)",
        }],
        sliders=[{
            "active": 0, "x": 0.05, "len": 0.90, "y": -0.02, "yanchor": "top",
            "currentvalue": {"prefix": "", "suffix": " UTC",
                             "visible": True, "xanchor": "center",
                             "font": {"color": "white", "size": 11}},
            "transition": {"duration": 0},
            "bgcolor": "rgba(40,40,60,0.8)", "bordercolor": "rgba(100,100,150,0.4)",
            "tickcolor": "rgba(200,200,255,0.5)",
            "font": {"color": "white", "size": 9},
            "steps": slider_steps,
        }],
    )
    return fig


# ══════════════════════════════════════════════════════════════════════════════
# Plot 2 — MP4 video
# ══════════════════════════════════════════════════════════════════════════════

def build_video(
    cap_t, cap_x, cap_y, cap_z, cap_mx, cap_my, cap_mz,
    loi_t, loi_x, loi_y, loi_z, loi_mx, loi_my, loi_mz,
    art_t, art_x, art_y, art_z, art_mx, art_my, art_mz,
    art_loi_t, art_loi_x, art_loi_y, art_loi_z,
    art_loi_mx, art_loi_my, art_loi_mz,
    burn_t: float,
    burn_t_art: float,
    wsb_circ_info: dict,
    art_circ_info: dict,
    R0: np.ndarray,
    wsb_tli_dv: float = 0.0,
    art_tli_dv: float = 0.0,
    art_parking_dv: float = 0.0,
    art_t_s0: float = 0.0,
    de440s_moon_t: np.ndarray = None,
    de440s_moon_x: np.ndarray = None,
    de440s_moon_y: np.ndarray = None,
    de440s_moon_z: np.ndarray = None,
) -> None:
    from matplotlib.animation import FuncAnimation, FFMpegWriter
    import matplotlib.gridspec as gridspec

    N_FRAMES  = 600
    FPS       = 30
    MAX_TRAIL = 600

    t_min    = cap_t[0]
    t_max    = min(t_min + 120.0, max(loi_t[-1], art_loi_t[-1]))
    frames_t = np.linspace(t_min, t_max, N_FRAMES)

    if de440s_moon_t is not None:
        _emx = lambda t: np.interp(t, de440s_moon_t, de440s_moon_x)
        _emy = lambda t: np.interp(t, de440s_moon_t, de440s_moon_y)
    else:
        _emx = lambda t: np.interp(t, cap_t, cap_mx)
        _emy = lambda t: np.interp(t, cap_t, cap_my)
    cap_xmc     = cap_x - cap_mx;              cap_ymc     = cap_y - cap_my
    loi_xmc     = loi_x     - _emx(loi_t);     loi_ymc     = loi_y     - _emy(loi_t)
    art_xmc     = art_x     - _emx(art_t);     art_ymc     = art_y     - _emy(art_t)
    art_loi_xmc = art_loi_x - _emx(art_loi_t); art_loi_ymc = art_loi_y - _emy(art_loi_t)

    fig = plt.figure(figsize=(19.2, 10.8), dpi=100, facecolor=BG)
    gs  = gridspec.GridSpec(1, 2, figure=fig,
                            width_ratios=[1.3, 1.0], wspace=0.03,
                            left=0.02, right=0.93, top=0.92, bottom=0.06)
    ax3 = fig.add_subplot(gs[0], projection="3d")
    ax2 = fig.add_subplot(gs[1])

    # ── 3D style ──────────────────────────────────────────────────────────────
    ax3.set_facecolor(BG)
    for attr in ("xaxis", "yaxis", "zaxis"):
        pane = getattr(ax3, attr).pane
        pane.fill = False; pane.set_edgecolor("#252540")
        getattr(ax3, attr)._axinfo["grid"]["color"]     = (0.30, 0.30, 0.60, 0.18)
        getattr(ax3, attr)._axinfo["grid"]["linewidth"] = 0.5
        getattr(ax3, attr).label.set_color("white")
        getattr(ax3, attr).label.set_fontsize(11)
    ax3.tick_params(colors="white", labelsize=9, pad=0)

    r_lim = float(np.max(np.abs([cap_x, cap_y]))) * 0.88
    z_lim = max(float(np.max(np.abs(cap_z))), float(np.max(np.abs(art_z)))) + 50_000
    z_lim = max(z_lim, r_lim * 0.20)
    ax3.set_xlim(-r_lim, r_lim); ax3.set_ylim(-r_lim, r_lim); ax3.set_zlim(-z_lim, z_lim)
    ax3.set_xlabel("X [km]", labelpad=1, fontsize=11)
    ax3.set_ylabel("Y [km]", labelpad=1, fontsize=11)
    ax3.set_zlabel("Z [km]", labelpad=1, fontsize=11)
    ax3.set_box_aspect([1.8, 1.8, max(0.35, z_lim / r_lim * 1.8)])
    ax3.view_init(elev=22, azim=-50)

    # ── Static 3D objects ─────────────────────────────────────────────────────
    sx, sy, sz = sphere_surface(R_EARTH, nu=48, nv=24)
    ax3.plot_surface(sx, sy, sz, color=COL_EARTH, alpha=0.85,
                     linewidth=0, zorder=2, shade=True)
    ax3.text(0, 0, R_EARTH * 1.8, "Earth", color="white", fontsize=13,
             ha="center", va="bottom", fontweight="bold")

    _t_orb = np.linspace(0, 2 * np.pi, 361)
    _morb  = R0 @ (np.array([np.cos(_t_orb), np.sin(_t_orb), np.zeros(361)]) * L_KM)
    ax3.plot(_morb[0], _morb[1], _morb[2],
             color=COL_MOON, alpha=0.18, linewidth=0.8, linestyle="--")
    _lbl = 40
    ax3.text(_morb[0][_lbl], _morb[1][_lbl], _morb[2][_lbl], "Lunar orbit",
             color=COL_MOON, fontsize=9, alpha=0.55, ha="left", va="bottom")

    # WSB apogee (BC furthest distance) static marker
    _apo_idx = int(np.argmax(np.sqrt(cap_x**2 + cap_y**2 + cap_z**2)))
    _apo_km  = float(np.sqrt(cap_x[_apo_idx]**2 + cap_y[_apo_idx]**2 + cap_z[_apo_idx]**2))
    ax3.scatter([cap_x[_apo_idx]], [cap_y[_apo_idx]], [cap_z[_apo_idx]],
                color=COL_CAP, s=55, marker="D", zorder=8, depthshade=False)
    ax3.text(cap_x[_apo_idx], cap_y[_apo_idx], cap_z[_apo_idx],
             f"  BC furthest dist. ({_apo_km/1e3:.0f}e3 km)",
             color=COL_CAP, fontsize=9, ha="left", va="bottom", zorder=9)

    # ── Animated 3D objects ───────────────────────────────────────────────────
    trail_c3,  = ax3.plot([], [], [], color=COL_CAP,     linewidth=2.5, alpha=0.90, zorder=5)
    trail_l3,  = ax3.plot([], [], [], color=COL_LOI,     linewidth=2.5, alpha=0.90, zorder=5)
    trail_a3,  = ax3.plot([], [], [], color=COL_ART,     linewidth=2.5, alpha=0.90, zorder=5)
    trail_al3, = ax3.plot([], [], [], color=COL_ART_LOI, linewidth=2.5, alpha=0.90, zorder=5)
    dot_c3,    = ax3.plot([], [], [], "o", color=COL_CAP,     markersize=6, zorder=10,
                          markeredgecolor="white", markeredgewidth=0.6)
    dot_l3,    = ax3.plot([], [], [], "o", color=COL_LOI,     markersize=7, zorder=11,
                          markeredgecolor="white", markeredgewidth=0.7)
    dot_a3,    = ax3.plot([], [], [], "o", color=COL_ART,     markersize=6, zorder=10,
                          markeredgecolor="white", markeredgewidth=0.6)
    dot_al3,   = ax3.plot([], [], [], "o", color=COL_ART_LOI, markersize=7, zorder=11,
                          markeredgecolor="white", markeredgewidth=0.7)
    dot_m3,    = ax3.plot([], [], [], "o", color=COL_MOON, markersize=5, zorder=8)

    # ── 2D style ──────────────────────────────────────────────────────────────
    ax2.set_facecolor(BG)
    ax2.set_aspect("equal")
    ax2.tick_params(colors="white", labelsize=11)
    ax2.set_xlabel("X from Moon [km]", color="white", fontsize=13)
    ax2.set_ylabel("Y from Moon [km]", color="white", fontsize=13)
    ax2.yaxis.set_label_position("right")
    ax2.yaxis.tick_right()
    ax2.set_xlim(-R_HILL_KM * 1.15, R_HILL_KM * 1.15)
    ax2.set_ylim(-R_HILL_KM * 1.15, R_HILL_KM * 1.15)
    for spine in ax2.spines.values():
        spine.set_edgecolor("#252540")
    ax2.grid(True, color=(0.30, 0.30, 0.60, 0.15), linewidth=0.5)

    phi2d = np.linspace(0, 2 * np.pi, 180)
    ax2.plot(R_HILL_KM * np.cos(phi2d), R_HILL_KM * np.sin(phi2d),
             color=COL_HILL, linewidth=1.5, linestyle=":",
             label=f"Hill sphere ({R_HILL_KM/1e3:.0f}e3 km)")
    moon_rd = R_MOON * 3
    ax2.fill(moon_rd * np.cos(phi2d), moon_rd * np.sin(phi2d),
             color=(0.63, 0.63, 0.63, 0.5), zorder=5)
    ax2.plot(moon_rd * np.cos(phi2d), moon_rd * np.sin(phi2d),
             color="#AAAAAA", linewidth=1, zorder=5)

    # Pre-compute burn Moon-relative positions for annotation placement
    _wsb_burn_xmc = float(cap_xmc[-1])                   # circular Moon (consistent with cap arc)
    _wsb_burn_ymc = float(cap_ymc[-1])
    _art_burn_xmc = float(art_loi_x[0] - _emx(burn_t_art))
    _art_burn_ymc = float(art_loi_y[0] - _emy(burn_t_art))

    # ── Animated 2D objects ───────────────────────────────────────────────────
    trail_c2,   = ax2.plot([], [], color=COL_CAP,     linewidth=3, alpha=0.90, zorder=6)
    trail_l2,   = ax2.plot([], [], color=COL_LOI,     linewidth=3, alpha=0.90, zorder=6)
    trail_a2,   = ax2.plot([], [], color=COL_ART,     linewidth=3, alpha=0.90, zorder=6)
    trail_al2,  = ax2.plot([], [], color=COL_ART_LOI, linewidth=3, alpha=0.90, zorder=6)
    dot_c2,     = ax2.plot([], [], "o", color=COL_CAP,     markersize=9,  zorder=10,
                           markeredgecolor="white", markeredgewidth=0.8)
    dot_l2,     = ax2.plot([], [], "o", color=COL_LOI,     markersize=10, zorder=11,
                           markeredgecolor="white", markeredgewidth=0.9)
    dot_a2,     = ax2.plot([], [], "o", color=COL_ART,     markersize=9,  zorder=10,
                           markeredgecolor="white", markeredgewidth=0.8)
    dot_al2,    = ax2.plot([], [], "o", color=COL_ART_LOI, markersize=10, zorder=11,
                           markeredgecolor="white", markeredgewidth=0.9)
    dot_wsb_burn2, = ax2.plot([], [], "*", color=COL_BURN,   markersize=12, zorder=12)
    dot_art_burn2, = ax2.plot([], [], "*", color=COL_BURN_A, markersize=12, zorder=12)

    wsb_dv_str = wsb_circ_info.get("LOI DeltaV km/s", "?")
    art_dv_str = art_circ_info.get("LOI DeltaV km/s", "?")

    wsb_dv_ann = ax2.text(_wsb_burn_xmc, _wsb_burn_ymc + R_HILL_KM * 0.07, "",
                          color=COL_BURN,   fontsize=12, ha="center", va="bottom",
                          fontweight="bold", zorder=13)
    art_dv_ann = ax2.text(_art_burn_xmc, _art_burn_ymc + R_HILL_KM * 0.07, "",
                          color=COL_BURN_A, fontsize=12, ha="center", va="bottom",
                          fontweight="bold", zorder=13)

    # ── Titles / legend ───────────────────────────────────────────────────────
    from matplotlib.lines import Line2D
    wsb_loi_dv   = float(wsb_circ_info.get("LOI DeltaV km/s", 0) or 0)
    art_loi_dv   = float(art_circ_info.get("LOI DeltaV km/s", 0) or 0)
    wsb_total_dv = wsb_tli_dv + wsb_loi_dv
    art_total_dv = art_parking_dv + art_tli_dv + art_loi_dv
    fig.text(0.5, 0.98, "Ballistic Capture vs Artemis II",
             color="white", fontsize=17, ha="center", va="top", fontweight="bold")
    fig.text(0.5, 0.955,
             f"Using Ballistic Capture:     TLI {wsb_tli_dv:.3f}  +  LOI {wsb_loi_dv:.3f}  =  {wsb_total_dv:.3f} km/s"
             f"          "
             f"Using Free-drift: Prk {art_parking_dv:.3f}  +  TLI {art_tli_dv:.3f}  +  LOI {art_loi_dv:.3f}  =  {art_total_dv:.3f} km/s",
             color="white", fontsize=12, ha="center", va="top")
    time_txt = fig.text(0.5, 0.928, "", color="#CCCCEE", fontsize=12,
                        ha="center", va="top")

    legend_handles = [
        Line2D([0],[0], color=COL_CAP,     linewidth=2.5, label="Ballistic Capture Transfer)"),
        Line2D([0],[0], color=COL_LOI,     linewidth=2.5, label="Ballistic Capture Lunar Orbit"),
        Line2D([0],[0], color=COL_ART,     linewidth=2.5, label="Free-drift Artemis Transfer"),
        Line2D([0],[0], color=COL_ART_LOI, linewidth=2.5, label="Free-drift Lunar Orbit"),
        Line2D([0],[0], color=COL_HILL,    linewidth=1.5, linestyle=":", label="Hill sphere"),
        Line2D([0],[0], marker="*", color=COL_BURN,   markersize=9, linestyle="none", label="Ballistic Capture orbit insertion"),
        Line2D([0],[0], marker="*", color=COL_BURN_A, markersize=9, linestyle="none", label="Free-drift orbit insertion"),
    ]
    ax2.legend(handles=legend_handles, loc="upper right", fontsize=11,
               framealpha=0.5, facecolor="#14141E", edgecolor="#333355",
               labelcolor="white")

    _art_t0_utc = TLI_UTC + datetime.timedelta(seconds=art_t_s0)

    # ── Update function ───────────────────────────────────────────────────────
    def update(fi: int):
        ft            = frames_t[fi]
        past_wsb_burn = ft >= burn_t
        past_art_burn = ft >= burn_t_art

        # Positions
        cx,  cy,  cz  = interp_pos(cap_t,     cap_x,     cap_y,     cap_z,     min(ft, burn_t))
        lx,  ly,  lz  = interp_pos(loi_t,     loi_x,     loi_y,     loi_z,     ft)
        ax_, ay_, az_ = interp_pos(art_t,      art_x,     art_y,     art_z,     min(ft, burn_t_art))
        alx, aly, alz = interp_pos(art_loi_t,  art_loi_x, art_loi_y, art_loi_z, ft)

        if de440s_moon_t is not None:
            mxw = float(np.interp(ft, de440s_moon_t, de440s_moon_x))
            myw = float(np.interp(ft, de440s_moon_t, de440s_moon_y))
            mzw = float(np.interp(ft, de440s_moon_t, de440s_moon_z))
        else:
            mxw = np.interp(min(ft, burn_t), cap_t, cap_mx) if not past_wsb_burn \
                  else np.interp(np.clip(ft, loi_t[0], loi_t[-1]), loi_t, loi_mx)
            myw = np.interp(min(ft, burn_t), cap_t, cap_my) if not past_wsb_burn \
                  else np.interp(np.clip(ft, loi_t[0], loi_t[-1]), loi_t, loi_my)
            mzw = np.interp(min(ft, burn_t), cap_t, cap_mz) if not past_wsb_burn \
                  else np.interp(np.clip(ft, loi_t[0], loi_t[-1]), loi_t, loi_mz)
        al_mx = float(_emx(ft))
        al_my = float(_emy(ft))

        # Trails
        cap_mask     = cap_t     <= min(ft, burn_t)
        loi_mask     = loi_t     <= ft
        art_mask     = art_t     <= min(ft, burn_t_art)
        art_loi_mask = art_loi_t <= ft

        def _ds3(xs, ys, zs, mask):
            tx, ty, tz = xs[mask], ys[mask], zs[mask]
            if len(tx) > MAX_TRAIL:
                i = downsample(np.arange(len(tx)), MAX_TRAIL)
                tx, ty, tz = tx[i], ty[i], tz[i]
            return tx, ty, tz

        ctx,  cty,  ctz  = _ds3(cap_x,    cap_y,    cap_z,    cap_mask)
        ltx,  lty,  ltz  = _ds3(loi_x,    loi_y,    loi_z,    loi_mask)
        atx,  aty,  atz  = _ds3(art_x,    art_y,    art_z,    art_mask)
        altx, alty, altz = _ds3(art_loi_x, art_loi_y, art_loi_z, art_loi_mask)

        trail_c3.set_data_3d(ctx, cty, ctz)
        trail_l3.set_data_3d(ltx, lty, ltz)
        trail_a3.set_data_3d(atx, aty, atz)
        trail_al3.set_data_3d(altx, alty, altz)

        dot_c3.set_data_3d([cx], [cy], [cz])
        dot_a3.set_data_3d([ax_], [ay_], [az_])
        dot_m3.set_data_3d([mxw], [myw], [mzw])

        if past_wsb_burn:
            dot_l3.set_data_3d([lx], [ly], [lz])
        else:
            dot_l3.set_data_3d([], [], [])

        if past_art_burn:
            dot_al3.set_data_3d([alx], [aly], [alz])
        else:
            dot_al3.set_data_3d([], [], [])

        def _ds2(xmc, ymc, mask):
            tx, ty = xmc[mask], ymc[mask]
            if len(tx) > MAX_TRAIL:
                i = downsample(np.arange(len(tx)), MAX_TRAIL)
                tx, ty = tx[i], ty[i]
            return tx, ty

        ctx2,  cty2  = _ds2(cap_xmc,     cap_ymc,     cap_mask)
        ltx2,  lty2  = _ds2(loi_xmc,     loi_ymc,     loi_mask)
        atx2,  aty2  = _ds2(art_xmc,     art_ymc,     art_mask)
        altx2, alty2 = _ds2(art_loi_xmc, art_loi_ymc, art_loi_mask)

        trail_c2.set_data(ctx2, cty2)
        trail_l2.set_data(ltx2, lty2)
        trail_a2.set_data(atx2, aty2)
        trail_al2.set_data(altx2, alty2)

        _cx_mc = float(np.interp(min(ft, burn_t), cap_t, cap_mx))
        _cy_mc = float(np.interp(min(ft, burn_t), cap_t, cap_my))
        dot_c2.set_data([cx - _cx_mc], [cy - _cy_mc])
        dot_a2.set_data([ax_ - al_mx], [ay_ - al_my])

        if past_wsb_burn:
            dot_l2.set_data([lx - mxw], [ly - myw])
            dot_wsb_burn2.set_data([_wsb_burn_xmc], [_wsb_burn_ymc])
            wsb_dv_ann.set_text(f"ΔV={wsb_dv_str} km/s")
        else:
            dot_l2.set_data([], [])
            dot_wsb_burn2.set_data([], [])
            wsb_dv_ann.set_text("")

        if past_art_burn:
            dot_al2.set_data([alx - al_mx], [aly - al_my])
            dot_art_burn2.set_data([_art_burn_xmc], [_art_burn_ymc])
            art_dv_ann.set_text(f"ΔV={art_dv_str} km/s")
        else:
            dot_al2.set_data([], [])
            dot_art_burn2.set_data([], [])
            art_dv_ann.set_text("")

        frame_utc = _art_t0_utc + datetime.timedelta(days=ft)
        time_txt.set_text(f"{frame_utc.strftime('%Y-%m-%d %H:%M UTC')}  —  Day {ft - t_min:.1f}")
        return (trail_c3, trail_l3, trail_a3, trail_al3,
                dot_c3, dot_l3, dot_a3, dot_al3, dot_m3,
                trail_c2, trail_l2, trail_a2, trail_al2,
                dot_c2, dot_l2, dot_a2, dot_al2,
                dot_wsb_burn2, dot_art_burn2,
                wsb_dv_ann, art_dv_ann, time_txt)

    anim   = FuncAnimation(fig, update, frames=N_FRAMES, blit=False, interval=1000 // FPS)
    writer = FFMpegWriter(fps=FPS, bitrate=8000,
                          metadata=dict(title="BCCapture + LOI vs Artemis II"),
                          extra_args=["-vcodec", "libx264", "-preset", "fast", "-crf", "18"])
    print(f"Rendering {N_FRAMES} frames at {FPS} fps -> {OUT_MP4} ...")
    anim.save(str(OUT_MP4), writer=writer, dpi=100)
    print(f"Saved video -> {OUT_MP4}")
    plt.close(fig)


# ══════════════════════════════════════════════════════════════════════════════
# Main
# ══════════════════════════════════════════════════════════════════════════════

def main() -> None:
    print("Loading Artemis II trajectory ...")
    (R0, u_sun_eci,
     art_t, art_x, art_y, art_z,
     art_mx, art_my, art_mz) = load_artemis()
    print(f"  Artemis: {len(art_t)} points, T+{art_t[-1]:.1f} d")

    # Artemis departure time (absolute seconds) for LOI time conversion
    art_df   = pd.read_csv(ART_CSV)
    art_t_s0 = float(art_df["time_s"].iloc[0])

    print("Loading DE440S Moon ephemeris ...")
    (ephem_t, ephem_mx, ephem_my, ephem_mz, _, _, _) = load_moon_ephem(art_t_s0)
    print(f"  Ephemeris: {len(ephem_t)} pts, t=[{ephem_t[0]:.1f}, {ephem_t[-1]:.1f}] d")

    # Artemis LOI time
    _art_loi_t0_s = float(pd.read_csv(ART_LOI_CSV, nrows=1)["time_s"].iloc[0])
    _art_loi_days = (_art_loi_t0_s - art_t_s0) / 86_400.0
    print(f"  Artemis LOI @ {_art_loi_days:.2f} d from CSV start")

    # WSB burn time from circularize_info (needed for synodic N selection)
    _wsb_circ_info_pre = load_circ_info(CIRC_INFO)
    _wsb_burn_time_days = float(_wsb_circ_info_pre.get("Burn time (days)", 0) or 0)

    print("Computing WSB departure epoch (circular-Moon, same as wsb_vs_artemis.py) ...")
    meta = pd.read_csv(WSB_HIF_CSV, nrows=1).iloc[0]
    _theta_sun_deg = float(meta["theta_sun_deg"])
    departure_offset_days, R0_wsb = compute_wsb_epoch_simple(
        _theta_sun_deg, R0, u_sun_eci,
        burn_time_days=_wsb_burn_time_days,
        target_loi_days=_art_loi_days + 15.0,
    )
    art_csv_start_utc = TLI_UTC + datetime.timedelta(seconds=art_t_s0)
    wsb_dep_utc       = art_csv_start_utc + datetime.timedelta(days=departure_offset_days)
    print(f"  WSB departure : {wsb_dep_utc.strftime('%Y-%m-%d %H:%M UTC')}")
    print(f"  Offset        : {departure_offset_days:+.2f} d from Artemis CSV start")

    print(f"Loading WSB capture trajectory ({CAPTURE_CSV.name}) ...")
    cap_t, cap_x, cap_y, cap_z, cap_mx, cap_my, cap_mz = \
        _load_wsb_nd_csv(CAPTURE_CSV, R0_wsb, departure_offset_days)
    print(f"  {len(cap_t)} points, T+{cap_t[-1] - departure_offset_days:.1f} d flight")

    burn_t = float(cap_t[-1])
    print(f"  WSB LOI burn time: {burn_t:.2f} days")

    print(f"Loading WSB ECI LOI orbit ({LOI_CSV.name}) ...")
    loi_t, loi_x, loi_y, loi_z, loi_mx, loi_my, loi_mz = load_wsb_loi_eci(art_t_s0)
    print(f"  {len(loi_t)} points, {loi_t[-1] - loi_t[0]:.1f} d of lunar orbit")

    wsb_circ_info = _wsb_circ_info_pre
    if wsb_circ_info:
        print(f"  WSB LOI dV = {wsb_circ_info.get('LOI DeltaV km/s','?')} km/s  "
              f"alt = {wsb_circ_info.get('Burn altitude km','?')} km")

    print(f"Loading Artemis LOI orbit ({ART_LOI_CSV.name}) ...")
    art_loi_t, art_loi_x, art_loi_y, art_loi_z, \
    art_loi_mx, art_loi_my, art_loi_mz = load_artemis_loi(art_t_s0)
    burn_t_art = float(art_loi_t[0])
    print(f"  {len(art_loi_t)} points, burn at T+{burn_t_art:.2f} d, "
          f"{art_loi_t[-1] - art_loi_t[0]:.1f} d of lunar orbit")

    art_circ_info = load_circ_info(ART_CIRC_INFO)
    if art_circ_info:
        print(f"  Artemis LOI dV = {art_circ_info.get('LOI DeltaV km/s','?')} km/s  "
              f"alt = {art_circ_info.get('Burn altitude km','?')} km")

    # ── Hohmann TLI ΔV comparison ─────────────────────────────────────────────
    # WSB: single Hohmann from circular 378 km to WSB apogee.
    wsb_apo_km = float(np.max(np.sqrt(cap_x**2 + cap_y**2 + cap_z**2)))
    wsb_tli_dv = hohmann_tli_dv(R_PARK_KM, wsb_apo_km)
    # Artemis: (1) Hohmann from circular 378 km → parking orbit apogee 109 400 km,
    #          (2) TLI burn from parking orbit (from config: 422.4 m/s).
    art_parking_dv = hohmann_tli_dv(R_PARK_KM, ART_PARKING_APO_KM)
    art_tli_dv     = ART_TLI_KMS
    print(f"  WSB apogee: {wsb_apo_km/1e3:.1f}e3 km  ->  TLI dV = {wsb_tli_dv:.4f} km/s")
    print(f"  Artemis: Prk dV = {art_parking_dv:.4f} km/s  +  TLI = {art_tli_dv:.4f} km/s")

    CIRC_DIR.mkdir(parents=True, exist_ok=True)

    de440s_moon_t = ephem_t
    de440s_moon_x = ephem_mx
    de440s_moon_y = ephem_my
    de440s_moon_z = ephem_mz
    print(f"  Moon track: {len(de440s_moon_t)} pts, "
          f"t=[{de440s_moon_t[0]:.2f}, {de440s_moon_t[-1]:.1f}] days")

    print("Building interactive Plotly HTML ...")
    fig = build_plotly(
        cap_t, cap_x, cap_y, cap_z, cap_mx, cap_my, cap_mz,
        loi_t, loi_x, loi_y, loi_z, loi_mx, loi_my, loi_mz,
        art_t, art_x, art_y, art_z, art_mx, art_my, art_mz,
        art_loi_t, art_loi_x, art_loi_y, art_loi_z,
        art_loi_mx, art_loi_my, art_loi_mz,
        burn_t, burn_t_art,
        wsb_circ_info, art_circ_info, R0,
        wsb_tli_dv=wsb_tli_dv, art_tli_dv=art_tli_dv,
        art_parking_dv=art_parking_dv, art_t_s0=art_t_s0,
        de440s_moon_t=de440s_moon_t, de440s_moon_x=de440s_moon_x,
        de440s_moon_y=de440s_moon_y, de440s_moon_z=de440s_moon_z,
    )
    fig.write_html(str(OUT_HTML), auto_play=False)
    print(f"Saved -> {OUT_HTML}")

    print("Building MP4 video ...")
    build_video(
        cap_t, cap_x, cap_y, cap_z, cap_mx, cap_my, cap_mz,
        loi_t, loi_x, loi_y, loi_z, loi_mx, loi_my, loi_mz,
        art_t, art_x, art_y, art_z, art_mx, art_my, art_mz,
        art_loi_t, art_loi_x, art_loi_y, art_loi_z,
        art_loi_mx, art_loi_my, art_loi_mz,
        burn_t, burn_t_art,
        wsb_circ_info, art_circ_info, R0,
        wsb_tli_dv=wsb_tli_dv, art_tli_dv=art_tli_dv,
        art_parking_dv=art_parking_dv, art_t_s0=art_t_s0,
        de440s_moon_t=de440s_moon_t, de440s_moon_x=de440s_moon_x,
        de440s_moon_y=de440s_moon_y, de440s_moon_z=de440s_moon_z,
    )


if __name__ == "__main__":
    main()
