[package]
name = "artemis"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "artemis"
path = "src/main.rs"

[[bin]]
name = "target"
path = "src/bin/target.rs"

[[bin]]
name = "mc"
path = "src/bin/mc.rs"

[[bin]]
name = "grid"
path = "src/bin/grid.rs"

[[bin]]
name = "moon_ephem"
path = "src/bin/moon_ephem.rs"

[dependencies]
nalgebra = { workspace = true }
hifitime = "4"
ode_solvers = "0.4"
ephemeris      = { path = "../../crates/ephemeris" }
orbital_models = { path = "../../crates/orbital_models" }
rand = "0.8"
rand_distr = "0.4"
