[package]
name = "interplanetary_transfer"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "~0.8"
rand_distr = "~0.4"
optimization = { path = "../.." }
num_cpus = "~1.16"
numerical-integration = "~0.1"
nalgebra = "~0.32"
maths-traits = "~0.2"
interpolation = "~0.3"
uuid = { version = "~1.7", features = ["v7"] }
rusqlite = { version = "~0.30", features = ["bundled"] }
chrono = "~0.4"
ephemeris = { path = "../../../crates/ephemeris" }
orbital_math = { path = "../../../crates/orbital_math" }
orbital_models = { path = "../../../crates/orbital_models" }
hifitime = "4"
